server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_lock?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Karen@1234


#mybatis
mybatis:
  #mapper????????????resources????
  mapper-locations: classpath:/mapper/*.xml
  # ??????
  map-underscore-to-camel-case: true
  # ??
  type-aliases-package: com.et.lock_dmeo.entity
