server:
  port: 81
  context-path: /


eureka:
  client:
    register-with-eureka: false #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone: http://eureka2001.etjava.com:2001/eureka/,
                    http://eureka2002.etjava.com:2002/eureka/,
                    http://eureka2003.etjava.com:2003/eureka/

ribbon:
  eager-load:
    enabled: true #立即加载
  ReadTimeout: 10000
  ConnectTimeout: 9000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
