server:
  port: 80
  servlet:
    context-path: /
# 服务注册
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: suibianxie
          uri: http://localhost:8081
          predicates:
            - Path=/order/**
      filter:
        secure-headers:
          disable: x-frame-options,strict-transport-security
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: e5c78c07-74ef-45ed-8389-b1ac2d1cd8c0