server:
  port: 8081
  servlet:
    context-path: /
# 服务注册
spring:
  application:
    name: order-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: e5c78c07-74ef-45ed-8389-b1ac2d1cd8c0 # 指定服务存放的命名空间 默认为public命名空间