server:
  port: 1006
  context-path: /

# 数据源配置
spring:
  application:
    name: microservice-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springcloud
    username: root
    password: Karen@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

# eureka注册
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student  #客户端服务名
    instance-id: microservice-student-hystrix:1006 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
      defaultZone: http://eureka2001.etjava.com:2001/eureka/,http://eureka2002.etjava.com:2002/eureka/,http://eureka2003.etjava.com:2003/eureka/ # 集群
      #defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心


management:
  endpoints:
    web:
      exposure:
        include: info #将info端点暴露给web（SpringBoot2.5.0或更高版本中info端点默认隐藏）
  info:
    env:
      enabled: true #是否在info端点中显示环境信息

# 配置info信息
info:
  app.name: microservice-student-provider-1006
  auther.name: Jerry
  auther.phone: 999


# 配置Hystrix默认超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000