#server:
#  port: 8081
#  servlet:
#    context-path: /
#
#spring:
#  application:
#    name: seckill-goods
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  rabbitmq:
#    host: 192.168.199.106
#    port: 5672
#    username: admin
#    password: admin
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_seckill?serverTimezone=Asia/Shanghai
#    username: root
#    password: Karen@1234
#  redis:  # redis配置
#    host: 192.168.199.106 # IP
#    port: 6379  # 端口
#    password:  # 密码
#    connect-timeout: 10s  # 连接超时时间
#    lettuce: # lettuce redis客户端配置
#      pool:  # 连接池配置
#        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-wait: 200s  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 8 # 连接池中的最大空闲连接 默认 8
#        min-idle: 0 # 连接池中的最小空闲连接 默认 0
#
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true  # 开启驼峰功能  userName  - >  user_name
#    auto-mapping-behavior: full  # 自动mapping映射
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.et.entity
#
